### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by Spiralexe** [vrondakis/syndicate#10]
-Power sockets in buildings don't update there count when you sell the building and something's connected to them

-if you own two buildings and sell one of them the other's devices which you still own, device's get disconnected as well [video](https://www.youtube.com/watch?v=Wx13hemY1BI)

~~Moving item into the bank and back into your inventory then attempting to put it back into the bank no longer works~~

-FPP fails to remove several ents on disconnect or force delete [gif](https://i.imgur.com/NWY7HRz.gif)
l

**Comment by uen** [comment]
Thanks for reporting

1) Going to fix this
2) I tested this and couldn't reproduce. I have doubts it has ever happened because the building system isn't designed in a way that would allow it to happen. Can you get a video?
3) Should be fixed in the latest update

**Comment by Spiralexe** [comment]
updated

**Comment by uen** [comment]
I believe these have been fixed so I'm closing this for now. Feel free to reopen
