### ISSUE TITLE
i cant add buff on my gang 

### ISSUE THREAD

**Issue by hicham30** [vrondakis/syndicate#14]
[C]: in function 'error'
gamemodes/darkrpx/gamemode/libraries/mysqlite/mysqlite.lua:262: in function
[C]: in function 'fn'
addons/ulib/lua/ulib/shared/hook.lua:109: in function
07/01/2021 17:10:13: Lua Error: gamemodes/darkrpx/gamemode/libraries/mysqlite/mysqlite.lua:262: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE val = "1"' at line 1 (INSERT INTO manolis_popcorn_gang_upgrades(ukey, gangid, val) VALUES("680639447","4", "1") ON DUPLICATE KEY UPDATE UPDATE val = "1")
stack traceback:
[C]: at 0xf0c67a00
[C]: in function 'error'
gamemodes/darkrpx/gamemode/libraries/mysqlite/mysqlite.lua:262: in function
[C]: in function 'fn'
addons/ulib/lua/ulib/shared/hook.lua:109: in function
gamemodes/darkrpx/gamemode/libraries/mysqlite/mysqlite.lua:262: You have an error in your SQsyntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UPDATE val = "1"' at line 1 (INSERT INTO manolis_popcorn_gang_upgrades(ukey, gangid, val) VALUES("680639447","4", "1") ON DUPLICATE KEY UPDATE UPDATE val = "1")
stack traceback:
[C]: at 0xf0c67a00
[C]: in function 'error'
gamemodes/darkrpx/gamemode/libraries/mysqlite/mysqlite.lua:262: in function
[C]: in function 'fn'
addons/ulib/lua/ulib/shared/hook.lua:109: in function

**Comment by uen** [comment]
Fixed in ef6f220ac379fdf2fa217e8f584dff852334830b
