### ISSUE TITLE
Error with picking up items with Inventory Swep

### ISSUE THREAD

**Issue by bugreporters** [vrondakis/syndicate#3]
Any time I try to pickup any item I get the error I posted below. For example a blueprint that comes out from a printer or a blueprint I personally drop from my inventory I can't pick it back up. The same goes for bars or anything that can be picked up.

The error that displays on the servers console is this:
```
[ERROR] gamemodes/darkrp/gamemode/modules/popcorn-inventory/sv_data.lua:98: attempt to index local 'ply' (a nil value)
  1. retrievePlayerItems - gamemodes/darkrp/gamemode/modules/popcorn-inventory/sv_data.lua:98
   2. getFreeSlots - gamemodes/darkrp/gamemode/modules/popcorn-inventory/sv_inventory.lua:18
    3. unknown - gamemodes/darkrp/entities/weapons/inventory/shared.lua:89
```
No error message appears on the client side.

**Comment by uen** [comment]
Should be fixed in the latest version
