### ISSUE TITLE
Extracting Property/Building System

### ISSUE THREAD

**Issue by rosman83** [vrondakis/syndicate#9]
I would like to use only the property/Building system on a darkrp server I am working on. Could you provide a general outline on the best way to do so? What modification will the module require before being a drag and drop? Thanks for any guidance or help.

**Comment by uen** [comment]
Drag and drop it and see what errors you get :smile: You would need to remake the GUI so it doesn't use Syndicate components at the bare minimum and I imagine you would have some issues with DarkRP's door system conflicting.

Closing this as it's not an issue with syndicate (this isn't a forum)
